<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Arunsobh" ignored="0" name="Sanity" tests="1" failures="0" timestamp="2022-12-18T15:26:54 IST" time="0.08" errors="0">
  <testcase name="@BeforeMethod FirstCall" time="0.002" classname="Com.Restaurant.Baseclass.BaseClass">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Com.Restaurant.Baseclass.BaseClass.launchApp(BaseClass.java:74)
at Com.Restaurant.Baseclass.BaseClass.FirstCall(BaseClass.java:54)
at java.util.ArrayList.forEach(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod FirstCall -->
  <testcase name="VerifyUserLogin" time="0.0" classname="com.Restaurant.TestCases.VerifyValidUserLoginTest">
    <skipped/>
  </testcase> <!-- VerifyUserLogin -->
</testsuite> <!-- Sanity -->
